"""create document chunks table

Revision ID: 0ae06507cfcf
Revises: c0887a6ae770
Create Date: 2026-06-06 19:01:20.298109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '0ae06507cfcf'
down_revision: Union[str, Sequence[str], None] = 'c0887a6ae770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('job_description_id', sa.UUID(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', Vector(3072), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n                document_type = 'resume'\n                AND resume_id IS NOT NULL\n                AND job_description_id IS NULL\n            )\n            OR\n            (\n                document_type = 'job_description'\n                AND job_description_id IS NOT NULL\n                AND resume_id IS NULL\n            )\n            ", name='ck_document_chunks_valid_document_reference'),
    sa.CheckConstraint("document_type IN ('resume', 'job_description')", name='ck_document_chunks_document_type'),
    sa.ForeignKeyConstraint(['job_description_id'], ['jobdescription.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_description_id', 'chunk_index', name='uq_document_chunks_jd_chunk_index'),
    sa.UniqueConstraint('resume_id', 'chunk_index', name='uq_document_chunks_resume_chunk_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
